# Generated by Django 2.2.6 on 2019-11-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twilio_integration', '0001_create_phone_number_and_message_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_url', models.URLField(max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twilio_integration.PhoneNumber')),
            ],
        ),
    ]
