# Generated by Django 2.2.6 on 2019-11-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mediahub", "0001_create_media_resource_table")]

    operations = [
        migrations.AddField(
            model_name="mediaresource", name="created_at", field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AddField(model_name="mediaresource", name="updated_at", field=models.DateTimeField(auto_now=True)),
    ]
