# Generated by Django 2.2.6 on 2019-12-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mediahub", "0002_add_datetime_fields_to_model")]

    operations = [
        migrations.AlterField(
            model_name="mediaresource",
            name="phone_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_resources",
                to="twilio_integration.PhoneNumber",
            ),
        )
    ]
