# Generated by Django 3.0.6 on 2020-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mediahub", "0003_add_related_name_to_model")]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="uploaded-images")),
            ],
        )
    ]
