# Generated by Django 3.0.6 on 2020-05-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0001_create_events_table"), ("mediahub", "0004_create_image_model_and_events")]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="images", to="events.Event"
            ),
        )
    ]
