notifications:
  email: false

dist: xenial
sudo: required

services:
  - postgresql
  - redis-server
addons:
  postgresql: "10"

language: python
python:
  - "3.8"

env:
  - IN_PRODUCTION=0 PYTHONPATH=. DJANGO_SETTINGS_MODULE=streetteam.settings DB_URI="postgresql://postgres@127.0.0.1:5432/streetteam_test" TWILIO_AUTH_TOKEN=fake-token

install:
  - pip install -r requirements_dev.txt
  - pip install codecov

before_script:
  - psql -c 'create database streetteam_test;' -U postgres

script:
  - python streetteam/manage.py migrate
  - pytest --cov=./streetteam
  - flake8
  - black --check .
  - codecov
