version: '3.6'

volumes:
  pgdata:
  localstack-data:


services:
  db:
    # infrastructure
    image: postgres:10.3-alpine
    environment:
      POSTGRES_DB: streetteam
      POSTGRES_USER: streetteam_user
      POSTGRES_PASSWORD: streetteam_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "9432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: webserver
    depends_on:
      - db
    environment:
      IN_PRODUCTION: 0
      PYTHONPATH: /app/streetteam
      SECRET_KEY: shhhhh-its-a-secret
      DJANGO_SETTINGS_MODULE: streetteam.settings
      DB_URI: postgres://streetteam_user:streetteam_password@db:5432/streetteam
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_SERVICE_SID: ${TWILIO_SERVICE_SID}
    volumes:
      - .:/app/
    ports:
      - 8100:8100
    stdin_open: true
    tty: true

  # https://hub.docker.com/r/localstack/localstack/
  # localstack running a fake S3
  localstack:
    image: localstack/localstack:0.11.1
    environment:
      - EDGE_PORT=4566
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
     - localstack-data:/tmp/localstack/data
