version: '3.6'

networks:
  sivnet:
    external: true
  local:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: webserver
    environment:
      IN_PRODUCTION: '1'
      PYTHONPATH: /app/streetteam
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: streetteam.settings
      DB_URI: ${STREETTEAM_DB_URI}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    volumes:  # TODO: once we move to image, we wont' need to do this
      - .:/app/
    stdin_open: true
    tty: true
    networks:
      - sivnet
      - local
    labels:
      - traefik.enable=true
      - traefik.docker.network=sivnet
      - traefik.backend=streetteam
      - traefik.frontend.rule=Host:streetteam.sivji.com
      - traefik.frontend.headers.SSLProxyHeaders=X-Forwarded-Proto:https
      - traefik.port=8100
