---
- name: ensure Git is installed
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: clone or pull latest code
  git:
    repo: "{{ code_repository }}"
    dest: "{{ app_dir }}"

- name: deploy latest image
  shell: ". /home/{{ user }}/.bash_profile && make prod-up"
  args:
      chdir: "{{ app_dir }}"
