# Generated by Django 2.2.6 on 2019-11-18 02:53

import uuid
from django.db import migrations


def generate_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_relation__add_uuid_field_null_values")]

    operations = [migrations.RunPython(generate_uuid, reverse_code=migrations.RunPython.noop)]
