# Generated by Django 2.2.6 on 2019-11-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_user_relation__make_uuid_field_unique")]

    operations = [
        migrations.AddField(model_name="user", name="username", field=models.EmailField(max_length=254, null=True))
    ]
