# Generated by Django 3.0.6 on 2020-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("happened_at", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
            ],
            options={"abstract": False},
        )
    ]
