# Generated by Django 3.0.6 on 2020-05-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0001_create_events_table")]

    operations = [migrations.RenameField(model_name="event", old_name="happened_at", new_name="happens_on")]
