# Generated by Django 3.0.6 on 2020-05-22 19:00

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [("events", "0006_rename_event_table")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "draft"),
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("deleted", "deleted"),
                    ("completed", "completed"),
                ],
                default="draft",
                max_length=50,
            ),
        )
    ]
