# Generated by Django 3.0.6 on 2020-05-22 23:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0007_add_event_status_fsm_field")]

    operations = [
        migrations.AddField(
            model_name="event", name="log", field=django.contrib.postgres.fields.jsonb.JSONField(default=list)
        )
    ]
