# Generated by Django 2.2.6 on 2019-11-03 16:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReceivedMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("twilio_message_id", models.CharField(max_length=34)),
                ("data", models.JSONField()),
                (
                    "phone_number",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="twilio_integration.PhoneNumber"),
                ),
            ],
        ),
    ]
