# Generated by Django 3.0.6 on 2020-05-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("teams", "0001_set_up_teams_model")]

    operations = [
        migrations.AddField(
            model_name="userteam",
            name="position_state",
            field=django_fsm.FSMField(
                choices=[
                    ("community_member", "community_member"),
                    ("team_lead", "team_lead"),
                    ("organizer", "organizer"),
                    ("admin", "admin"),
                ],
                default="community_member",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="teams.Team"
            ),
        ),
        migrations.AlterField(
            model_name="userteam",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
