# Generated by Django 3.0.6 on 2020-05-20 00:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_create_position_field_as_fsm_field"),
    ]

    operations = [migrations.RenameModel(old_name="UserTeam", new_name="UserTeamMembership")]
