# Generated by Django 3.0.6 on 2020-05-21 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("teams", "0003_rename_membership_table")]

    operations = [
        migrations.AddField(
            model_name="team", name="join_code", field=models.UUIDField(default=uuid.uuid4, unique=True)
        )
    ]
