# Generated by Django 3.0.6 on 2020-05-22 00:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("teams", "0004_add_join_code")]

    operations = [migrations.AlterUniqueTogether(name="userteammembership", unique_together={("user", "team")})]
