# Generated by Django 3.0.6 on 2020-05-22 02:48

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [("teams", "0005_add_user_team_unique_together_constraint")]

    operations = [
        migrations.AlterField(
            model_name="userteammembership",
            name="position_state",
            field=django_fsm.FSMField(
                choices=[
                    ("withdrew_from_team", "withdrew_from_team"),
                    ("released_by_team", "released_by_team"),
                    ("community_member", "community_member"),
                    ("team_lead", "team_lead"),
                    ("organizer", "organizer"),
                    ("admin", "admin"),
                ],
                default="community_member",
                max_length=50,
            ),
        )
    ]
