name: Build and Test Street Team
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      # - name: Build the stack
      #   run: make up
      # - name: Test application
      #   run: make test
