name: Build and Test Street Team
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: 123
      TWILIO_AUTH_TOKEN: 456
      TWILIO_SERVICE_SID: 789
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - name: Build the stack
        run: make up-ci
      - name: Test application
        run: make test
