name: Build and Test Street Team
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: make up
      - name: Test application
        run: make test
