name: Build and Test Street Team
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04
    env:
      IN_PRODUCTION: '0'
      PYTHONPATH: ${GITHUB_WORKSPACE}
      DJANGO_SETTINGS_MODULE: streetteam.settings
      DB_URI: postgres://streetteam_user:streetteam_password@0.0.0.0:5432/streetteam
      TWILIO_AUTH_TOKEN: test_token

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: streetteam
          POSTGRES_PASSWORD: streetteam_user
          POSTGRES_DB: streetteam_password
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.0"
      # cache this
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Migrate database
        run: python streetteam/manage.py migrate
      - name: Test application
        run: pytest

