name: Build and Test Street Team
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build application
        run: make up
      - name: Test application
        run: echo test
