name: Build and Test Street Team
on: [pull_request]
jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04
    env:
      IN_PRODUCTION: '0'
      PYTHONPATH: ${GITHUB_WORKSPACE}
      DJANGO_SETTINGS_MODULE: streetteam.settings
      DB_URI: postgres://streetteam_user:streetteam_password@0.0.0.0:5432/streetteam
      TWILIO_AUTH_TOKEN: test_token

    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 10.3
          postgresql user: streetteam
          postgresql password: streetteam_password
          postgresql db: streetteam
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8.0"
      - name: Checkout repo
        uses: actions/checkout@v1
      # cache this
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Migrate database
        run: python streetteam/manage.py migrate
      - name: Test application
        run: pytest
