name: Build and Test Street Team
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build application
        run: make up
        env:
          TWILIO_AUTH_TOKEN: test_token
      - name: Test application
        run: make test
